### ISSUE TITLE
Error WebApi C# Project - HRESULT: 0x8007000B

### ISSUE THREAD

**Issue by NukeDev** [TopperDEL/uplink.net#13]
Can't use Uplink lib on WebApi C# Project Net 4.7

System.TypeInitializationException: 'L'inizializzatore di tipo di 'uplink.SWIG.storj_uplinkPINVOKE' ha generato un'eccezione.'
BadImageFormatException: Tentativo di caricare un programma con un formato non corretto. (Eccezione da HRESULT: 0x8007000B)
   at uplink.SWIG.storj_uplinkPINVOKE.new_UplinkConfig()
   at uplink.NET.Models.Uplink..ctor(UplinkConfig uplinkConfig, String tempDir)
   at uplink.NET.Models.Scope.Init(UplinkConfig uplinkConfig)
   at uplink.NET.Models.Scope..ctor(String apiKey, String satelliteAddress, String secret, UplinkConfig uplinkConfig)
   at dev.loady.storj.Program.<RUN>d__5.MoveNext() 

The project is running on x64, and can't be modified. I think this is the problem.

![Screenshot_10](https://user-images.githubusercontent.com/7417090/75122463-fea06480-569d-11ea-9ee8-32f43fefedde.png)

**Comment by TopperDEL** [comment]
@NukeDev  I think this is a nuget-issue - there are binaries available for x64 and x86, but I'm too dump to get nuget deploy them correctly. If you habe more knowdlege in that field I would be happy to merge your PR. :)

You may try to copy the files manually. In your case what's missing is the "storj_uplink.dll" next to your WebAPI-DLL. The latest 64bit-version can be found here:
https://github.com/TopperDEL/uplink.net/tree/master/uplink.NET/uplink.NET/x64

Let me know if that helps for the moment. That library is quite new and the first one I maintain on my own. I have zero-knowledge with Nuget-packages, and that's where the problem originally comes from.
Thanks for using uplink.Net!

**Comment by TopperDEL** [comment]
To be more precise: it seems you got the x86-version deployed instead of the x64-one.

**Comment by NukeDev** [comment]
Will test asap, i'll let you know.

Thanks :)

**Comment by TopperDEL** [comment]
@NukeDev Did you succeed with your project? May I help any further or can this issue be closed?

**Comment by NukeDev** [comment]
Sorry @TopperDEL, i missed it! I've recently moved my project from .Net to Go.. I'm sorry :)
