### ISSUE TITLE
Having issue with uploading large file.

### ISSUE THREAD

**Issue by eskye** [TopperDEL/uplink.net#18]
Facing difficulty uploading large file. I have tried the `UploadObjectChunkedAsync` and the `UploadObjectAsync` method. I still can't make it work. 

I have checked the wiki documentation, no documentation for such.

Is there a reference to any documentation on how this works? 

Language: ASP.NET CORE.

**Comment by TopperDEL** [comment]
Do you have any code-sample that is not working? Do you get an exception?
If your program crashes completely and "silently" (without a .Net-Exception) then I would recomment to try the latest nuget as there has been an issue with uploads and garbage collection, that should be fixed now.

I'm currently a bit behind providing a good documentation - sorry for that. It's still on my list. You may have a look at the other Tardigrade-Repos in my account and look how I did the upload there. E.g. this one:
https://github.com/TopperDEL/uplink.NET.AppTest/blob/02b2ca2ac084617d023159e11559756ecf645584/uplink.NET.AppTest/uplink.NET.AppTest.Shared/MainPage.xaml.cs#L48

Is your code openly visible somewhere, so I may have a look?

**Comment by eskye** [comment]
I was actually trying to upload a large file of `150mb` size.
Here's the code snippet:

```C#
    
int chunkSize = 10 * 1024 * 1024;

                long uploadSize = 0;

                byte[] chunk = new byte[chunkSize];

                UploadOperation uploadOperationRestricted = null;

                bool uploadRegister = false;


                using (FileStream fileReader = new FileStream(file, FileMode.Open, FileAccess.Read))

                {

                    BinaryReader binaryReader = new BinaryReader(fileReader);

                    long bytesToRead = fileReader.Length;


                    do

                    {

                        chunk = binaryReader.ReadBytes(chunkSize);


                        uploadOperationRestricted = await objectService.UploadObjectAsync(bucket, info.Name, new UploadOptions(), chunk, false);

                        if (!uploadRegister)

                        {

                            uploadOperationRestricted.UploadOperationProgressChanged += UploadOperationRestricted_UploadOperationProgressChanged;

                            uploadOperationRestricted.UploadOperationEnded += UploadOperationRestricted_UploadOperationEnded;

                            uploadRegister = true;

                        }

                        uploadSize += chunkSize;

                        bytesToRead -= chunkSize;

                        var mb = (float)uploadSize / info.Length * 100;

                        Console.WriteLine($"{mb} % uploaded");

                    } while (bytesToRead > 0);

                    binaryReader.Close();

                }

                await uploadOperationRestricted.StartUploadAsync();

```

The major issue is immediately it hit the `await uploadOperationRestricted.StartUploadAsync()`, I don't really have any exception than the console message **thread exited code(0) **, then, the program freezes and later crashes.

Nuget version used:
`  <PackageReference Include="uplink.NET" Version="2.3.1" />`
Framework: `Asp.net core Worker service`

Thanks a lot for your help.

**Comment by TopperDEL** [comment]
Ok - I have to tell you, that you are doing it wrong, I'm sorry. :)
You should be able to do something like this:
```
using (FileStream fileReader = new FileStream(file, FileMode.Open, FileAccess.Read))
{
     var uploadOperationRestricted = await objectService.UploadObjectAsync(bucket, info.Name, new UploadOptions(), fileReader, false);
     uploadOperationRestricted.UploadOperationProgressChanged += UploadOperationRestricted_UploadOperationProgressChanged;
     uploadOperationRestricted.UploadOperationEnded += UploadOperationRestricted_UploadOperationEnded;
     await uploadOperationRestricted.StartUploadAsync();
}
```

In your case your basically trying to upload chunks of your file as a file itself. Either provide the stream itself or the complete byte[] - uplink.Net takes care of splitting it up in chunks and such. With the UploadOperationChanged-Event you get info about the current progress.

Does that help?

**Comment by eskye** [comment]
I will try it out and get back with feedback on this thread.

Thanks a lot.

**Comment by eskye** [comment]
Issue resolved. Thank you so much, it was really helpful.

**Comment by TopperDEL** [comment]
You're welcome! So I'm closing this issue then.
