### ISSUE TITLE
The type initializer for 'uplink.SWIG.storj_uplinkPINVOKE' threw an exception.

### ISSUE THREAD

**Issue by Joshhua5** [TopperDEL/uplink.net#25]
I did a quick look into this and it appears I don't have the required storj_uplink.dll within my build.

This may be an issue since I'm running .net5 core.

**Comment by TopperDEL** [comment]
Can you give me more info about your setup? Which platform are you on? Do you also have added the relevant platform-specific Nugets like uplink.net.win?

**Comment by StanislavChankov** [comment]
@TopperDEL , I have the same issue. The resolution at the moment is to add the platform specific package - like `uplink.NET.Win`, but this is not what we want. We also use .NET 5 for our back-end, which runs on Linux containers. Using the Win specific package will make this unable to build for linux. Can you please create `netstandard` or `net5.0` package for this purpose?

**Comment by TopperDEL** [comment]
Uplink.net itself is cross platt and should work on linux. But you have to add the uplink.Net.Linux package there, too, if you need to support linux.

The reason for all this: uplink.net used a generated binary under the hood to call into the uplink-c library written in go. For this I need specific binaries for every plattform.

But that should not be a big problem - just add the relevant packages fir the platforms you want to use. They could even be side by side in the same project - depending on the platgorm during runtime,.net should select the correct binary. You may have a look at duplicati, that works on win, mac and linux - though it still uses an older uplink.net version.

Come back if my comment does not help you, though. I'm here to help but am on the go currently.

**Comment by Joshhua5** [comment]
Hey,

I'm using Windows 10, but I wasn't aware of the additional packages like .win  / .linux that needed to be added, that most likely addresses this issue. I see you've updated the README to address this.

**Comment by TopperDEL** [comment]
Yeah, the documentation unfortunately is a bit outdated, currently. But that part just got added by another user who also falled in that gap. :)

**Comment by StanislavChankov** [comment]
I still have issues with `uplink.NET.Linux`
It seems as it is build with .NET Framework. I can't build it on Linux.

Have you tested it?

![image](https://user-images.githubusercontent.com/35253870/122632662-04188e00-d0dd-11eb-9fec-ab2307fd92ba.png)

**Comment by Erikvv** [comment]
That is only a warning, it works for me with the warning.

**Comment by StanislavChankov** [comment]
@Erikvv , I cannot build the project inside a Linux container.

**Comment by TopperDEL** [comment]
@StanislavChankov What error did you get then? And what means "inside a Linux container"?

**Comment by StanislavChankov** [comment]
The package `uplink.NET.Linux` does not build. The reason is why it is on .net framework, instead of `netstandard`.

Linux container means Docker for Linux container.

**Comment by TopperDEL** [comment]
Sorry, but I do not get what "does not build" mean here. You mean, you'r solution does not compile? What exact error do you get? The message above from you is only a warning, as Erik mentioned. Do you have anything to show?

**Comment by StanislavChankov** [comment]
My actually builds, but runtime it throws some exception that I'm unable to catch the exception, but I guess it's `The type initializer for 'uplink.SWIG.storj_uplinkPINVOKE' threw an exception.`

The last output that I get is:
```
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.28/System.Runtime.InteropServices.RuntimeInformation.dll'. Cannot find or open the PDB file.
```

I don't know how this even build, when the platform-specific package `uplink.NET.Linux` is `net4.x`, but I recommend you to create it as `netstandard2.1` or `net5.0`.

Do you have examples for running the Linux version of the package?

**Comment by TopperDEL** [comment]
The message you receive signals either you are running a 32bit-system (there are not 32bit-linux-binaries available) or that indeed the path is wrong where the DLL resides in.
I currently have no working Linux-Sample at hand. You may have a look at Duplicati, but that's quite huge for just testing that. You may bring the uplink.NET-package down to version 2.5.0 - that version includes all binaries itself and that *should* work.

But the first main question ist: are you on 32bit or 64bit?

The net4.x-version of the package should not be the problem, as far as I know.

**Comment by StanislavChankov** [comment]
@TopperDEL 
I am using Docker Desktop Windows x64 for Linux Containers. This means that I am running Linux x64.

How have you ensure that this package is working? Can you please test it?
There is no point to invest more time from my side at this point.

I can provide you an example project to test. I can't attach it here, but I can do so in our slack channel.

**Comment by Erikvv** [comment]
This works for me on Linux. Create project:

```
dotnet new
dotnet add package uplink.NET
dotnet add package uplink.NET.Linux
```

Put some code in Program.cs Main():

```
using System;

using uplink.NET.Models;
using uplink.NET.Services;
using System.Threading.Tasks;

namespace yourfolder
{
    class Program
    {
        static async Task<int> Main(string[] args)
        {
            Access.SetTempDirectory(System.IO.Path.GetTempPath());
            var config = new Config();
            config.UserAgent = "uplink-csharp";
            config.DialTimeoutMilliseconds = 5000;
            config.TempDirectory = System.IO.Path.GetTempPath();

            var access = new Access(/* credentials */);

            var bucketService = new BucketService(access);
            ListBucketsOptions listOptions = new ListBucketsOptions();
            var buckets = await bucketService.ListBucketsAsync(listOptions);
            foreach (var bucket in buckets.Items) {
                Console.WriteLine(bucket.Name);
            }
            

            return 1;
        }
    }
}

```

run 

```
dotnet run
```

output:

```
mybucket1
mybucket2
```

**Comment by TopperDEL** [comment]
Thanks @Erikvv - this is exactly what I would do to check the package. @StanislavChankov if you have any code to show, that would be great. Otherwise please try the code above and let us know if that works for you.

**Comment by StanislavChankov** [comment]
Can you please provide me example working inside Linux container? So we need docker-compose.yaml and Dockerfile as well. If you have easier way to ensure that your package is working under Linux, please share.

**Comment by TopperDEL** [comment]
I don't have any knowdledge about Docker and Linux containers, I'm sorry. But I expect the above to work in a container, too.

**Comment by Erikvv** [comment]
Example at https://gitlab.com/erikvv/uplink-csharp-demo

Instructions:

1. `git clone git@gitlab.com:erikvv/uplink-csharp-demo.git`
2. `cd uplink-csharp-demo`
3. Put credentials in Program.cs at `new Access(/* credentials */)`
4. `docker-compose up`
5. There should be this output or an error:

```
$ docker-compose up
Creating network "uplink-csharp-demo_default" with the default driver
Creating uplink-csharp-demo_dotnet_1 ... done
Attaching to uplink-csharp-demo_dotnet_1
dotnet_1  | /uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
dotnet_1  | /uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
dotnet_1  | mybucket1
dotnet_1  | mybucket2
uplink-csharp-demo_dotnet_1 exited with code 0
```

**Comment by StanislavChankov** [comment]
@Erikvv Do you run Windows or Linux containers?

My result for Linux container:
![image](https://user-images.githubusercontent.com/35253870/124509114-06b3fc80-ddda-11eb-8a86-08407ca0ee3c.png)

```
The build failed. Fix the build errors and run again.


/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

/uplink-demo/Program.cs(19,30): error CS1729: 'Access' does not contain a constructor that takes 0 arguments [/uplink-demo/uplink-demo.csproj]

/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
```

**Comment by StanislavChankov** [comment]
@Erikvv Do you run Windows or Linux containers?

**Comment by TopperDEL** [comment]
@StanislavChankov Did you notice step 3 in Erik's list above? Did you provide credentials?

`var access = new Access(/* credentials */);`

**Comment by StanislavChankov** [comment]
Yes I did. The project builds on my local environment - Windows 10.
![image](https://user-images.githubusercontent.com/35253870/124509434-a3769a00-ddda-11eb-9fa7-75c2b9704112.png)

**Comment by TopperDEL** [comment]
But I saw an error like this in your messages:

`/uplink-demo/Program.cs(19,30): error CS1729: 'Access' does not contain a constructor that takes 0 arguments [/uplink-demo/uplink-demo.csproj]`

**Comment by StanislavChankov** [comment]
Yes, since my container cached the images, but I removed it.
Clearly the project builds on windows, but not on Linux.

**Comment by TopperDEL** [comment]
But then once again: there must be a build error message. Can you provide that?

**Comment by StanislavChankov** [comment]
Only warnings: 
```
/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.

/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.


/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.


/uplink-demo/uplink-demo.csproj : warning NU1701: Package 'uplink.NET.Linux 2.6.1451' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
```

**Comment by TopperDEL** [comment]
I'm sorry that I still do not get what you do with the docker container, what steps are involved and such. But if you say "it does not build" there must be a build error message. All I see above are warnings that are indeed annoying but should not stop building.

I see your warings above. So the build finishes? then you have problems during runtime - and what exactyl happens there, then?

**Comment by TopperDEL** [comment]
Warnings are warnings and should not block you.

**Comment by StanislavChankov** [comment]
@TopperDEL just install Docker on you machine and test it inside Linux containers :)

**Comment by TopperDEL** [comment]
I have other stuff to do, honestly. Do you still get the "type initializer"-error during runtime?

**Comment by StanislavChankov** [comment]
@TopperDEL honestly I also have other stuff to do, but not to test your nuget package :)
I am presenting Sfera technologies, so we could be a good client. As I see so far, no need to invest more time.

**Comment by TopperDEL** [comment]
@StanislavChankov Erik gave you a working example above. I have tested it the same on my linux machine. Please answer my question regarding the exact error you get during runtime. Otherwise I do not know how to help you further.
Bear in mind that this is an Open Source Tool (the uplink.NET-library) provided to you for free, I do all this support here in my leisure time currently - so please be polite and fair.

**Comment by TopperDEL** [comment]
![image](https://user-images.githubusercontent.com/1833242/124512294-4e398900-ddd8-11eb-8402-a158e43c5b7b.png)

Working here...

**Comment by Joshhua5** [comment]
I think this ticket could be closed out here.

@StanislavChankov <https://github.com/StanislavChankov> If you have a
runtime error, it would fall under a different issue from this ticket and
you can create a new one.

**Comment by eddy7904** [comment]
Hi, friends, 
I have a question, uplink.net can be used within a .net framework 4.7.2 project or is it exclusive to Net Core
