### ISSUE TITLE
uplink.net working for framework 4.7.2

### ISSUE THREAD

**Issue by eddy7904** [TopperDEL/uplink.net#27]
Hi, friends,
I have a question, uplink.net can be used within a .net framework 4.7.2 project or is it exclusive to Net Core

**Comment by Erikvv** [comment]
It should work though I haven't tried it myself.

**Comment by TopperDEL** [comment]
That is my expectation, too. It should work without problems.

**Comment by TopperDEL** [comment]
@eddy7904 Do you still have problems here or may we close this issue?

**Comment by TopperDEL** [comment]
Closing this as there was no further response.
