### ISSUE TITLE
Add .NET 6.0 as target for the lib

### ISSUE THREAD

**Issue by Belphemur** [TopperDEL/uplink.net#30]
**Is your feature request related to a problem? Please describe.**
Avoiding the warning about "using this is for .NET Framwork" message.

**Describe the solution you'd like**
Add .net-6.0-linux and net6.0-win to each of the os lib

**Describe alternatives you've considered**
Ignoring the warning when on a .NET 6.0 project

**Additional context**
I'm wondering what is the reason for using .NET Framework for the lib

**Comment by TopperDEL** [comment]
Hey! Thanks for your issue! I'm currently struggeling with the Nuspecs and the transition to Net6. If you may help me out here, that would be great. Just an hour ago I tried to add net6 to the iOs-Nuget, but I am not sure if I did it right.

If you can give me tips or a PR to bring my library to the latest bits, I would be very happy. Thank you!

**Comment by Belphemur** [comment]
Ho darn, I admit I have mostly used the `csproj` files (and sometimes the `Assembly.cs` file).
I can check how the nuspecs works.

**Comment by TopperDEL** [comment]
I just updated the Nugets to include net6 - may you check again if that solves it for you?

**Comment by Belphemur** [comment]
Looks good to me :)
