### ISSUE TITLE
Library not loaded: storj_uplink-simx64.dylib

### ISSUE THREAD

**Issue by MarkIvanDev** [TopperDEL/uplink.net#35]
**Describe the bug**
When debugging the iOS app, it crashes at startup and emits the following error: `Library not loaded: storj_uplink-simx64.dylib`

**To Reproduce**
1. Create a Xamarin.iOS app
2. Install the nuget packages
3. Add the `uplink.NET.Models.Access.Init_iOs(Foundation.NSBundle.MainBundle.BundlePath);` at app's startup
4. Debug the app
5. See error

**Expected behavior**
The app should be able to locate the library and run.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Simulator
 - OS: iOS

**Additional context**

**Comment by TopperDEL** [comment]
Thanks for the report!
I can reproduce the issue, but unfortunately have no idea how to solve it. If you have any ideas or suggestions, I would be more than happy.

The dylib contained in the Nuget is a fat lib - it has a version for ARM64 and for x86_x64 in it. But it seems the storj_uplink.dylib does not get deployed to the simulator-build.

**Comment by MarkIvanDev** [comment]
Unfortunately, I don't have any idea how to fix this. But I would like to ask how the iOS heads of the samples work around this bug? Is there a published iOS app that uses this library?

**Comment by MarkIvanDev** [comment]
Oh, that is good to know. If it deploys correctly on a device, I guess I can use that to test the app. Thank you.

I have read somewhere in the Apple docs that packaging libs for the simulator and a real device in a single package is unsupported. Although, I don't have experience packaging dynamic libs for Xamarin iOS. I will try to learn more about this subject and how we can deploy the library correctly to the simulator.

**Comment by TopperDEL** [comment]
Just found this helpful repo: https://github.com/bielikb/xcframeworks
It might not be that complicated for me to switch to XCFramework. Will try this later this week and hope you come along with the device build until then.

**Comment by TopperDEL** [comment]
May you try uplink.NET 2.9.2950? It still does not work on my end, but I have another issue with VS4Mac currently, that might interfere here.

**Comment by TopperDEL** [comment]
Hey @MarkIvanDev - do you still have that issue? I've been busy and could not yet digg into this. But I may do another round if the issue still persists. Otherwise I would close this issue.
