### ISSUE TITLE
Win-Arm64 not packaged correctly in Nuspec

### ISSUE THREAD

**Issue by kenkendk** [TopperDEL/uplink.net#39]
**Describe the bug**
The nupkg from Nuget installs the x64 binary on arm64, using latest `2.12.3363`.

**To Reproduce**
1. `dotnet new console`
2. `dotnet add package uplink.NET.Win`
3. `dotnet add package uplink.NET.Linux`
4. `dotnet build -r win-arm64`
5. `dotnet build -r linux-x64`
6. In the `publish` folder, the Windows x64 `storj_uplink.dll` is installed for both win-arm64 and linux-x64.

**Expected behavior**
The package should only install the relevant files.
The same problem occurs when including the Windows+Linux package and targeting Linux.

**Additional context**
Looking inside the nupkg, it has the correct files, but the build process appears to be picking up the wrong version for some reason.

Console session showing the included files:
```
> shasum uplink.net.win.2.12.3363.nupkg/runtimes/win-x64/native/storj_uplink.dll
8c9f069cc657f16787347d1f916a67f756aedbd9  uplink.net.win.2.12.3363.nupkg/runtimes/win-x64/native/storj_uplink.dll

> shasum uplink.net.win.2.12.3363.nupkg/runtimes/win-x86/native/storj_uplink.dll
ba10f3492ea1e5c838a08a129fc951e3d5060716  uplink.net.win.2.12.3363.nupkg/runtimes/win-x86/native/storj_uplink.dll

> shasum uplink.net.win.2.12.3363.nupkg/runtimes/win-arm64/native/storj_uplink.dll
6ff71d75099f12ebf98c8ff5383f1af5fd0e5e13  uplink.net.win.2.12.3363.nupkg/runtimes/win-arm64/native/storj_uplink.dll

> shasum test-project/publish/linux-arm64-gui/storj_uplink.dll
8c9f069cc657f16787347d1f916a67f756aedbd9  test-project/linux-arm64-gui/storj_uplink.dll

> shasum test-project/publish/linux-x64-gui/storj_uplink.dll
8c9f069cc657f16787347d1f916a67f756aedbd9  test-project/linux-x64-gui/storj_uplink.dll

> shasum test-project/publish/linux-x64-gui/storj_uplink.so
3998df8c86149d31d249728d85f3a26b4d118fac  test-project/linux-x64-gui/storj_uplink.so

> shasum test-project/publish/win-arm64-gui/storj_uplink.dll
8c9f069cc657f16787347d1f916a67f756aedbd9  test-project/win-arm64-gui/storj_uplink.dll

> file test-project/publish/win-arm64-gui/storj_uplink.dll
test-project/win-arm64-gui/storj_uplink.dll: PE32+ executable (DLL) (console) x86-64 (stripped to external PDB), for MS Windows

> file test-project/publish/win-x64-gui/storj_uplink.dll
test-project/win-arm64-gui/storj_uplink.dll: PE32+ executable (DLL) (console) x86-64 (stripped to external PDB), for MS Windows

> file uplink.net.win.2.12.3363.nupkg/runtimes/win-arm64/native/storj_uplink.dll
uplink.net.win.2.12.3363.nupkg/runtimes/win-arm64/native/storj_uplink.dll: PE32+ executable (DLL) (GUI) Aarch64, for MS Windows

> ls test-project/linux-x64-gui/storj_uplink.*
test-project/linux-x64-gui/storj_uplink.dll	
test-project/linux-x64-gui/storj_uplink.so

> file test-project/publish/win-x64-gui/storj_uplink.dll
test-project/win-arm64-gui/storj_uplink.dll: PE32+ executable (DLL) (console) x86-64 (stripped to external PDB), for MS Windows

> file test-project/publish/win-x64-gui/storj_uplink.so
test-project/win-arm64-gui/storj_uplink.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=551f4f30f0fe83233ff6da071cfa448ef246ae6e, with debug_info, not stripped
```

My project file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="uplink.NET.Linux" Version="2.12.3365" />
    <PackageReference Include="uplink.NET.Win" Version="2.12.3363" />
  </ItemGroup>

</Project>
```

I see a warning during build:
```
/Users/kenneth/Downloads/test-storj/test-storj.csproj : warning NU1701: Package 'uplink.NET.Win 2.12.3363' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net8.0'. This package may not be fully compatible with your project.
```

I am guessing that it somehow triggers the [target file](https://github.com/TopperDEL/uplink.net/blob/master/nuspec/net40/uplink.NET.Win.targets) which overrides the normal target selection.

**Comment by TopperDEL** [comment]
Thanks @kenkendk for this issue and your feedback! I'm in a personal war against nuspec and target-file. 🤣🙈 I do not really know what I could/would have to change here. The whole nuget/nuspec-thing feels so unnecessary complex.
I'll try to find a more stable way for the packages. If you have any idea how to do it better, let me know! Basically it is just "place the {platform-binary} in the output dir" for all supported platforms.

**Comment by kenkendk** [comment]
@TopperDEL Ha! I am not well versed in the MSBuild scripts either, but I think at least part of the problem is that the [conditions look at the operating system running MSBuild, not the target](https://learn.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2022#systemoperatingsystem-property-functions):

> The System.OperatingSystem property functions return information about the operating system on which MSBuild is running. For example, if your project targets Linux and you build it on macOS, the property functions will return information about macOS.

So it would work for developing, except the lack of the Win-Arm64 condition.
But when building for another operating system, it will fail.

The best answer I can find [is this SO thread](https://stackoverflow.com/questions/65160131/what-msbuild-condition-should-be-used-to-detect-target-os) that mentions using: `Condition="'$(RuntimeIdentifier)' == 'linux-arm'"`.

In [my own packages with multi-arch binaries, I do not have the target file at all](https://github.com/duplicati/system.data.sqlite-binaries/blob/main/packages/System.Data.SQLite.Core.Duplicati.linux.arm64.nuspec), and then it appears to work as expected, just placing the targets in the correct runtime folders.

I **think** that for .NET5+ you no longer need the build targets.

**Comment by kenkendk** [comment]
A related note, on Mac, I can see that the library is built with both x64 + arm64, but somehow it does not get installed on Arm64.


csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="uplink.NET.Linux" Version="2.12.3365" />
    <PackageReference Include="uplink.NET.Win" Version="2.12.3363" />
    <PackageReference Include="uplink.NET.Mac" Version="2.12.3363" />
  </ItemGroup>

</Project>
```

Running:
```
dotnet publish -r osx-x64
dotnet publish -r osx-arm64
```

Places the `libstorj_uplink.dylib` only in the x64 output.
That does not seem to have anything to do with the target file, but follow the [copy conventions where the file is only copied to x64](https://github.com/TopperDEL/uplink.net/blob/master/nuspec/uplink.NET.Mac.nuspec#L27).

An additional note: I do not get warnings about the package target version when building, except when I include the `uplink.NET.Win` package.

**Comment by TopperDEL** [comment]
So, I'm a little step further.
There should now be ARM and ARM64-builds for Linux which should fix [this issue](https://github.com/duplicati/duplicati/issues/4342). Haven't tried it yet, though.

Also the package should now deploy x64 and arm64 on MacOs correctly. We're still not done yet as Windows still might deploy the wrong binary for arm64.

**Comment by TopperDEL** [comment]
So now the prerelease-version of the packages should support:

- Win-x86, Win-x64, Win-arm64
- Linux-x64, Linux-arm, Linux-arm64
- osx-x64, osx-arm64

Finally it seems I got them all! :)

The warnings about the package target version are gone now, too. I *think* that uplink.NET does not really support .NetFramework anymore - but I think this is neglectable.

**Comment by TopperDEL** [comment]
Issue should be resolved with the version 2.13.* Closing it.

**Comment by kenkendk** [comment]
@TopperDEL I have tested it, and it *almost* works, but I think you have packaged the wrong binaries in the nupkg:
```
> shasum uplink.net.linux.2.13.3448/runtimes/linux-*/native/storj_uplink.so
5a56a5bf5ca48156bee579b706c7a4e0ef7c8353  uplink.net.linux.2.13.3448/runtimes/linux-arm/native/storj_uplink.so
5a56a5bf5ca48156bee579b706c7a4e0ef7c8353  uplink.net.linux.2.13.3448/runtimes/linux-arm64/native/storj_uplink.so
5a56a5bf5ca48156bee579b706c7a4e0ef7c8353  uplink.net.linux.2.13.3448/runtimes/linux-x64/native/storj_uplink.so
```

All 3 variants have the same binary, and it looks like the x64 variant:
```
> file uplink.net.linux.2.13.3448/runtimes/linux-*/native/storj_uplink.so
uplink.net.linux.2.13.3448/runtimes/linux-arm/native/storj_uplink.so:   ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b242b27943bce2a7cb5e3462a840bc34efd46009, with debug_info, not stripped
uplink.net.linux.2.13.3448/runtimes/linux-arm64/native/storj_uplink.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b242b27943bce2a7cb5e3462a840bc34efd46009, with debug_info, not stripped
uplink.net.linux.2.13.3448/runtimes/linux-x64/native/storj_uplink.so:   ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b242b27943bce2a7cb5e3462a840bc34efd46009, with debug_info, not stripped
```

All the versions in `.Win` and `.Mac` seems to be correct, so I **think** it is just the packaging that has picked up the wrong binaries.

**Comment by TopperDEL** [comment]
Thanks for the finding, @kenkendk!
I was concentrated on the correct pathing but did not realize, that the build itself was not respecting the target-architecture. I fixed this with some trial and error. Version 2.13.3484 should be fine now!
